---
title: "Research"
---

<html>
  <head>
    <style type="text/css">
      .paper { 
        color: #000080;
        font-weight:bold;
        font-size:14px;
        line-height : 10px;
      }
      .link{ 
        color: #64c4ed;
        font-weight:bold;
        font-size:10px;
        line-height : 10px;
      }
      .desc { 
        font-size:12px;
        line-height : 12px;
      }
      .abstract { 
        font-style:italic;
        font-size:12px;
        line-height : 15px;
        text-align: justify;
        text-justify: inter-word;
      }
      ul.a {
        list-style-type: circle;
        font-size: 12px;
        line-height : 12px;
        text-align: justify;
        text-justify: inter-word;
      }
    </style>
  </head>
  <body>
    <strong> Job Market Paper: </strong> 
    <br>
    <p>
      <span class="paper"> Does Fintech Lending Lower Financing Costs? Evidence From An Emerging Market </span> 
      <span class="link"> (available soon!) </span> <br>
      <span class="desc"> Joint with Jose Renato Haas Ornelas, from the Brazilian Central Bank </span> 
    <ul class= "a"> 
      <li> 2022 Financial Management Association Best Paper Award in Fintech. Semifinalist </li>
      <li> Presented at: Special PhD Presentations of the FMA Annual Meeting 2022 (scheduled), FMA Annual Meeting 2022 (scheduled), 
          North America Summer Meeting of the Econometric Society 2022, XXII Brazilian Finance Meeting 2022, Brazilian Central Bank Research Seminar               2021, World Finance and Banking Symposium 2021, Universidade de Sao Paulo (scheduled), Universidade Catolica de Brasilia. </li>
    </ul>
    <span class="abstract"> <strong> Abstract: </strong> Using proprietary data of virtually all unsecured working capital loans to small businesses in        Brazil, we find that online Peer-to-Peer (P2P) lenders focus on smaller and riskier firms. They penetrate relatively more in municipalities that         are distant from the main financial centers, where banking markets are oligopolistic. P2P clients get lower interest rates compared to traditional       banks. Moreover, once they borrow from P2Ps, they do find a lower rate on subsequent bank loans, indicating that banks try to recapture runaway          borrowers. Using the staggered implementation of high-speed optical fiber internet as a quasi-experiment enabling P2P entry, we find that incumbent       banks decrease their lending rates by 3 percentage points and expand credit to more businesses in response to P2P entry. We rationalize these            findings in a structural IO model of the banking sector, where banks and P2Ps have different profit functions and compete for clients with risk          heterogeneity. We use the estimated to model to calculate welfare gains. We find that P2Ps significantly increase social welfare in oligopolistic        markets by offering lower interest rates to the riskier borrowers, and forcing the banks to do the same. Welfare gains range from 10\% of the local       output in municipalities with only one incumbent bank to 1\% in those with five banks. </span> <br> 
    </p>
    <br>
    <strong> Publications: </strong> <br>
    <p>
      <span class="paper"> International Trade and the Risk in Bilateral Exchange Rates </span> 
      <a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3745935" class="link"> (SSRN) </a> <br> 
      <span class="desc"> Joint with Ramin Hassan, Erik Loauliche, and Colin Ward <br> 
      Forthcoming at the <strong> <em> Journal of Financial Economics </em> </strong> <br> </span>
      <ul class= "a"> 
      <li> Presented at: FIRS 2022\*, WFA 2022\*, MFA 2022, NBER Summer Institute 2021\*  </li>
      </ul>
      <span class="abstract"> <strong> Abstract: </strong> Exchange rate volatility falls after a trade deal, driven by a decline the systematic
      component of risk. The average trade deal increases trade by 50 percent over 5 years, leading to a 30 percent decline in the systematic risk of          exchange rate. We examine the connection between exchange rates and international trade in the light of an Armington model. The nature of trade          networks determine the risk in exchange rates, and countries at the periphery benefit the most from lower trade barriers. We estimate our model to       current data, and run a counterfactual experiment simulating a trade war between the U.S. and China. Our simulation shows a global increase in           currency risk, with most of the effects concentrated amongst countries at the periphery of the global trade network. </span>
    </p>
  </body>
</html>
    


