---
title: "Teaching"
---

<html>
  <head>
    <style type="text/css">
      .paper { 
        color: #000080;
        font-weight:bold;
        font-size:14px;
        line-height : 10px;
      }
      .link{ 
        color: #64c4ed;
        font-weight:bold;
        font-size:10px;
        line-height : 10px;
      }
      .desc { 
        font-size:12px;
        line-height : 12px;
        font-weight:bold;
      }
      .abstract { 
        font-style:italic;
        font-size:12px;
        line-height : 15px;
        text-align: justify;
        text-justify: inter-word;
      }
      ul.a {
        list-style-type: circle;
        font-size: 12px;
        line-height : 12px;
        text-align: justify;
        text-justify: inter-word;
      }
    </style>
  </head>
    <body>
      <br>
        <p>
          <span class="paper"> Instructor: FINA 3001 Finance Fundamentals </span> <br>
          <span class="desc"> University of Minnesota, Carlson School of Management (2020) </span> 
        <ul class= "a"> 
          <li> Ph.D Excellence in Teaching Award, University of Minnesota (2020) </li> 
          <li> John Willard Herrick Teaching Award, University of Minnesota (2020) </li>
        </ul>
      </p>
      <p>
        <span class="paper"> Teaching Assistant </span> <br>
        <span class="desc"> University of Minnesota, Carlson School of Management (2017-2022) </span> 
        <ul class= "a"> 
          <li> <strong> MSF/MBA: </strong> Quantitative Portfolio Analysis, Derivatives and Risk Management, Financial Management, Computing for Finance,               Financial Management, Financial Modeling, Introduction to Python </li>
          <li> <strong> Undergraduate: </strong> Corporate Finance, World Economy, International Finance, Portfolio Management, Options and Derivatives,                Behavioral Finance, Financial Markets and Interest Rates </li>
        </ul>
      </p>
      <p>
        <span class="paper"> Recitation Instructor: Microeconomics (MSc) </span> <br>
        <span class="desc"> University of Sao Paulo (2011) </span> 
      </p>
  </body>
</html>
